[package]
name = "rust"
version = "0.1.0"
authors = ["Elliana <me@mause.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "*", features = ["full"] }
serenity = "*"
tokio-postgres = "*"
typemap_rev = "*"
rustls = "*"
dotenv = "*"
postgres-native-tls = "*"
native-tls = "*"
bytes = "1"
tokio-pg-mapper-derive = "*"
tokio-pg-mapper = "*"
google_maps = { git = "https://github.com/headuck/google_maps" }
rust_decimal = "*"
futures-preview = "*"
log = "*"
tokio-compat-02 = "*"
simple_logger = "*"
